# Generated by Django 2.2.3 on 2019-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0003_auto_20190704_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='streak',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
