# Generated by Django 2.2.3 on 2019-07-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0004_auto_20190704_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='cleavage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='color',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_habit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='crystal_symmetry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='luster',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='mohs_scale_hardness',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='strunz_classification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='unit_cell',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
